import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'ml' | 'or' | 'pa' | 'as' | 'ma' | 'sa' | 'ks' | 'sd' | 'ur' | 'ko' | 'mn' | 'bo' | 'do' | 'ne' | 'st';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    active_members: 'Active Members',
    ending_membership: 'Ending Membership',
    renew_membership: 'Renew Membership',
    add_member: 'Add Member',
    gym_of_fame: 'Gym of Fame',
    analytics: 'Analytics',
    logout: 'Logout',
    menu: 'Menu',
    download_app: 'Download App',
    change_language: 'Change Language',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
    contact_us: 'Contact Us',
    back: 'Back',
    total_members: 'Total Members',
    monthly_revenue: 'Monthly Revenue',
    this_month: 'This Month',
    search_members: 'Search members...',
    renew: 'Renew',
    edit: 'Edit',
    delete: 'Delete',
    no_members: 'No members found',
    loading: 'Loading...',
    select_language: 'Select Language',
    name: 'Name',
    phone: 'Phone',
    amount: 'Amount',
    days: 'Days',
    start_date: 'Start Date',
    end_date: 'End Date',
    uploading: 'Uploading',
    add_photo: 'Add Photo',
    explore_mode: 'Explore Mode Active — Some functions strictly limited',
    fast_operations: 'Members menu',
    gym_owner: 'Gym Owner',
    physique_gallery: 'Physique Gallery',
    growth_tracking: 'Growth Tracking',
    membership_trend: 'Membership Trend',
    financial_health: 'Financial Health',
    today_revenue: 'Today Revenue',
    total_sales: 'Total Sales',
    owner_profile: 'Owner Profile',
    gym_name: 'Gym Name',
    address: 'Address',
    save_profile: 'Save Profile',
    edit_profile: 'Edit Profile',
    cancel: 'Cancel',
    app_tagline: 'Master Your Gym Management',
    app_desc: 'A powerful, all-in-one platform for gym owners to track memberships, analyze revenue, and showcase physique transformations.',
    sign_in: 'Become a Member (Sign-in)',
    log_in: 'Already a Member (Log-in)',
    explore_more: 'Explore More',
    member_tracking: 'Member Tracking',
    growth_analytics: 'Growth Analytics',
    revenue_insights: 'Revenue Insights',
    secure_access: 'Secure Access',
    profile_management: 'Profile Management',
    member_tracking_desc: 'Manage memberships, renewals, and active lists easily.',
    growth_analytics_desc: 'Track your gym growth with month-over-month comparisons.',
    revenue_insights_desc: 'Detailed financial analytics, from daily to total collections.',
    physique_gallery_desc: 'Showcase your members insane physiques in a dedicated gallery.',
    secure_access_desc: 'Your data is protected and available whenever you need it.',
    profile_management_desc: 'Professional gym owner profile with contact details and UPI support.',
    about_us: 'About Us',
    privacy_policy: 'Privacy Policy',
    terms_conditions: 'Terms & Conditions',
    premium_suite: 'Premium Management Suite',
    no_fame_entries: 'No Hall of Fame entries yet.',
    add_first_photo: 'Add First Photo',
    swipe_explore: 'Swipe left or right to explore',
    out_of_membership: 'Out of Membership',
    quick_renew: 'Quick Renew',
    membership_renewed: 'Membership is Renewed',
    member_photo: 'Member Photo',
    optional: 'Optional',
    click_upload: 'CLICK / UPLOAD',
    remove_photo: 'Remove Photo',
    age: 'Age',
    email: 'Email',
    renew_membership_btn: 'RENEW MEMBERSHIP',
    download_list: 'DOWNLOAD LIST',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    active_members: 'सक्रिय सदस्य',
    ending_membership: 'समाप्त होने वाली सदस्यता',
    renew_membership: 'सदस्यता नवीनीकरण',
    add_member: 'सदस्य जोड़ें',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेन्यू',
    download_app: 'ऐप डाउनलोड करें',
    change_language: 'भाषा बदलें',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'संपर्क करें',
    back: 'पीछे',
    total_members: 'कुल सदस्य',
    monthly_revenue: 'मासिक आय',
    this_month: 'इस महीने',
    search_members: 'सदस्य खोजें...',
    renew: 'नवीनीकरण',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    no_members: 'कोई सदस्य नहीं मिला',
    loading: 'लोड हो रहा है...',
    select_language: 'भाषा चुनें',
    name: 'नाम',
    phone: 'फ़ोन',
    amount: 'राशि',
    days: 'दिन',
    start_date: 'शुरू करने की तिथि',
    end_date: 'समाप्ति तिथि',
    uploading: 'अपलोड हो रहा है',
    add_photo: 'फोटो जोड़ें',
    explore_mode: 'एक्सप्लोर मोड सक्रिय - कुछ कार्य सीमित हैं',
    fast_operations: 'सदस्य मेनू',
    gym_owner: 'जिम मालिक',
    physique_gallery: 'फिजिक्स गैलरी',
    growth_tracking: 'विकास ट्रैकिंग',
    membership_trend: 'सदस्यता रुझान',
    financial_health: 'वित्तीय स्वास्थ्य',
    today_revenue: 'आज की आय',
    total_sales: 'कुल बिक्री',
    owner_profile: 'मालिक की प्रोफाइल',
    gym_name: 'जिम का नाम',
    address: 'पता',
    save_profile: 'प्रोफ़ाइल सहेजें',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    cancel: 'रद्द करें',
    app_tagline: 'अपने जिम प्रबंधन में महारत हासिल करें',
    app_desc: 'जिम मालिकों के लिए सदस्यता ट्रैक करने, आय का विश्लेषण करने और शरीर के परिवर्तनों को प्रदर्शित करने के लिए एक शक्तिशाली, सर्वांगीण मंच।',
    sign_in: 'सदस्य बनें (साइन-इन)',
    log_in: 'पहले से सदस्य हैं (लॉग-इन)',
    explore_more: 'और जानें',
    member_tracking: 'सदस्य ट्रैकिंग',
    growth_analytics: 'विकास विश्लेषण',
    revenue_insights: 'आय संबंधी जानकारी',
    secure_access: 'सुरक्षित पहुंच',
    profile_management: 'प्रोफ़ाइल प्रबंधन',
    member_tracking_desc: 'सदस्यता, नवीनीकरण और सक्रिय सूचियों को आसानी से प्रबंधित करें।',
    growth_analytics_desc: 'महीने-दर-महीने तुलना के साथ अपने जिम के विकास को ट्रैक करें।',
    revenue_insights_desc: 'दैनिक से लेकर कुल संग्रह तक विस्तृत वित्तीय विश्लेषण।',
    physique_gallery_desc: 'एक समर्पित गैलरी में अपने सदस्यों के प्रभावशाली शरीर का प्रदर्शन करें।',
    secure_access_desc: 'आपका डेटा सुरक्षित है और जब भी आपको इसकी आवश्यकता हो उपलब्ध है।',
    profile_management_desc: 'संपर्क विवरण और UPI समर्थन के साथ पेशेवर जिम मालिक की प्रोफ़ाइल।',
    about_us: 'हमारे बारे में',
    privacy_policy: 'गोपनीयता नीति',
    terms_conditions: 'नियम और शर्तें',
    premium_suite: 'प्रीमियम प्रबंधन सुइट',
    no_fame_entries: 'अभी तक कोई हॉल ऑफ फेम प्रविष्टियां नहीं हैं।',
    add_first_photo: 'पहली फोटो जोड़ें',
    swipe_explore: 'खोजने के लिए बाएं या दाएं स्वाइप करें',
    out_of_membership: 'सदस्यता से बाहर',
    quick_renew: 'त्वरित नवीनीकरण',
    membership_renewed: 'सदस्यता नवीनीकृत हो गई है',
    member_photo: 'सदस्य की फोटो',
    optional: 'वैकल्पिक',
    click_upload: 'क्लिक करें / अपलोड करें',
    remove_photo: 'फोटो हटाओ',
    age: 'आयु',
    email: 'ईमेल',
    renew_membership_btn: 'सदस्यता नवीनीकृत करें',
    download_list: 'सूची डाउनलोड करें',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    active_members: 'সক্রিয় সদস্য',
    ending_membership: 'মেয়াদ শেষ হওয়া সদস্যপদ',
    renew_membership: 'সদস্যপদ নবায়ন',
    add_member: 'সদস্য যোগ করুন',
    gym_of_fame: 'জিম অফ ফেম',
    analytics: 'বিশ্লেষণ',
    logout: 'লগআউট',
    menu: 'মেনু',
    download_app: 'অ্যাপ ডাউনলোড করুন',
    change_language: 'ভাষা পরিবর্তন করুন',
    dark_mode: 'ডার্ক মোড',
    light_mode: 'লাইট মোড',
    contact_us: 'যোগাযোগ করুন',
    back: 'পিছনে',
    total_members: 'মোট সদস্য',
    monthly_revenue: 'মাসিক আয়',
    this_month: 'এই মাসে',
    search_members: 'সদস্য খুঁজুন...',
    renew: 'নবায়ন',
    edit: 'সম্পাদনা',
    delete: 'মুছে ফেলুন',
    no_members: 'কোন সদস্য পাওয়া যায়নি',
    loading: 'লোড হচ্ছে...',
    select_language: 'ভাষা নির্বাচন করুন',
    name: 'নাম',
    phone: 'ফোন',
    amount: 'পরিমাণ',
    days: 'দিন',
    start_date: 'শুরুর তারিখ',
    end_date: 'শেষের তারিখ',
  },
  te: {
    dashboard: 'డ్యాష్‌బోర్డ్',
    active_members: 'క్రియాశీల సభ్యులు',
    ending_membership: 'ముగిసే సభ్యత్వం',
    renew_membership: 'సభ్యత్వ పునరుద్ధరణ',
    add_member: 'సభ్యుడిని చేర్చండి',
    gym_of_fame: 'జిమ్ ఆఫ్ ఫేమ్',
    analytics: 'విశ్లేషణ',
    logout: 'లాగ్అవుట్',
    menu: 'మెనూ',
    download_app: 'యాప్ డౌన్‌లోడ్ చేయండి',
    change_language: 'భాష మార్చండి',
    dark_mode: 'డార్క్ మోడ్',
    light_mode: 'లైట్ మోడ్',
    contact_us: 'మమ్మల్ని సంప్రదించండి',
    back: 'వెనుకకు',
    total_members: 'మొత్తం సభ్యులు',
    monthly_revenue: 'నెలవారీ ఆదాయం',
    this_month: 'ఈ నెల',
    search_members: 'సభ్యుల కోసం వెతకండి...',
    renew: 'పునరుద్ధరించండి',
    edit: 'సవరించండి',
    delete: 'తొలగించు',
    no_members: 'సభ్యులు ఎవరూ లేరు',
    loading: 'లోడ్ అవుతోంది...',
    select_language: 'భాషను ఎంచుకోండి',
    name: 'పేరు',
    phone: 'ఫోన్',
    amount: 'మొత్తం',
    days: 'రోజులు',
    start_date: 'ప్రారంభ తేదీ',
    end_date: 'ముగింపు తేదీ',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    active_members: 'सक्रिय सदस्य',
    ending_membership: 'संपणारी सदस्यत्वे',
    renew_membership: 'सदस्यत्व नूतनीकरण',
    add_member: 'सदस्य जोडा',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेनू',
    download_app: 'अॅप डाउनलोड करा',
    change_language: 'भाषा बदला',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'संपर्क साधा',
    back: 'मागे',
    total_members: 'एकूण सदस्य',
    monthly_revenue: 'मासिक उत्पन्न',
    this_month: 'या महिन्यात',
    search_members: 'सदस्य शोधा...',
    renew: 'नूतनीकरण करा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    no_members: 'कोणतेही सदस्य आढळले नाहीत',
    loading: 'लोड होत आहे...',
    select_language: 'भाषा निवडा',
    name: 'नाव',
    phone: 'फोन',
    amount: 'रक्कम',
    days: 'दिवस',
    start_date: 'सुरुवात तारीख',
    end_date: 'समाप्ती तारीख',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    active_members: 'செயலில் உள்ள உறுப்பினர்கள்',
    ending_membership: 'முடியும் உறுப்பினர் காலம்',
    renew_membership: 'உறுப்பினர் புதுப்பித்தல்',
    add_member: 'உறுப்பினரைச் சேர்',
    gym_of_fame: 'ஜிம் ஆஃப் ஃபேம்',
    analytics: 'பகுப்பாய்வு',
    logout: 'வெளியேறு',
    menu: 'மெனு',
    download_app: 'செயலியைப் பதிவிறக்கு',
    change_language: 'மொழியை மாற்றவும்',
    dark_mode: 'டார்க் மோட்',
    light_mode: 'லைட் மோட்',
    contact_us: 'தொடர்பு கொள்ளவும்',
    back: 'பின்செல்',
    total_members: 'மொத்த உறுப்பினர்கள்',
    monthly_revenue: 'மாதாந்திர வருவாய்',
    this_month: 'இந்த மாதம்',
    search_members: 'உறுப்பினர்களைத் தேடுங்கள்...',
    renew: 'புதுப்பி',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    no_members: 'உறுப்பினர்கள் யாரும் இல்லை',
    loading: 'ஏற்றப்படுகிறது...',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    name: 'பெயர்',
    phone: 'தொலைபேசி',
    amount: 'தொகை',
    days: 'நாட்கள்',
    start_date: 'ஆரம்ப தேதி',
    end_date: 'முடிவு தேதி',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    active_members: 'સક્રિય સભ્યો',
    ending_membership: 'સમાપ્ત થતી સભ્યપદ',
    renew_membership: 'સભ્યપદ નવીનીકરણ',
    add_member: 'સભ્ય ઉમેરો',
    gym_of_fame: 'જિમ ઓફ ફેમ',
    analytics: 'વિશ્લેષણ',
    logout: 'લોગઆઉટ',
    menu: 'મેનૂ',
    download_app: 'એપ્લિકેશન ડાઉનલોડ કરો',
    change_language: 'ભાષા બદલો',
    dark_mode: 'ડાર્ક મોડ',
    light_mode: 'લાઇટ મોડ',
    contact_us: 'સંપર્ક કરો',
    back: 'પાછા',
    total_members: 'કુલ સભ્યો',
    monthly_revenue: 'માસિક આવક',
    this_month: 'આ મહિને',
    search_members: 'સભ્યો શોધો...',
    renew: 'નવીનીકરણ કરો',
    edit: 'સુધારો',
    delete: 'કાઢી નાખો',
    no_members: 'કોઈ સભ્યો મળ્યા નથી',
    loading: 'લોડ થઈ રહ્યું છે...',
    select_language: 'ભાષા પસંદ કરો',
    name: 'નામ',
    phone: 'ફોન',
    amount: 'રકમ',
    days: 'દિવસો',
    start_date: 'શરૂઆતની તારીખ',
    end_date: 'અંતિમ તારીખ',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    active_members: 'ಸಕ್ರಿಯ ಸದಸ್ಯರು',
    ending_membership: 'ಮುಕ್ತಾಯಗೊಳ್ಳುವ ಸದಸ್ಯತ್ವ',
    renew_membership: 'ಸದಸ್ಯತ್ವ ನವೀಕರಣ',
    add_member: 'ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ',
    gym_of_fame: 'ಜಿಮ್ ಆಫ್ ಫೇಮ್',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    logout: 'ಲಾಗ್ಔಟ್',
    menu: 'ಮೆನು',
    download_app: 'ಅಪ್ಲಿಕೇಶನ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    change_language: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
    dark_mode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    light_mode: 'ಲೈಟ್ ಮೋಡ್',
    contact_us: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    back: 'ಹಿಂದಕ್ಕೆ',
    total_members: 'ಒಟ್ಟು ಸದಸ್ಯರು',
    monthly_revenue: 'ಮಾಸಿಕ ಆದಾಯ',
    this_month: 'ಈ ತಿಂಗಳು',
    search_members: 'ಸದಸ್ಯರನ್ನು ಹುಡುಕಿ...',
    renew: 'ನವೀಕರಿಸಿ',
    edit: 'ತಿದ್ದಿ',
    delete: 'ಅಳಿಸಿ',
    no_members: 'ಯಾವುದೇ ಸದಸ್ಯರು ಕಂಡುಬಂದಿಲ್ಲ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    select_language: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    name: 'ಹೆಸರು',
    phone: 'ಫೋನ್',
    amount: 'ಮೊತ್ತ',
    days: 'ದಿನಗಳು',
    start_date: 'ಪ್ರಾರಂಭದ ದಿನಾಂಕ',
    end_date: 'ಮುಕ್ತಾಯದ ದಿನಾಂಕ',
  },
  ml: {
    dashboard: 'ഡാഷ്ബോർഡ്',
    active_members: 'സജീവ അംഗങ്ങൾ',
    ending_membership: 'അവസാനിക്കുന്ന അംഗത്വം',
    renew_membership: 'അംഗത്വം പുതുക്കൽ',
    add_member: 'അംഗത്തെ ചേർക്കുക',
    gym_of_fame: 'ജിം ഓഫ് ഫെയിം',
    analytics: 'അനലിറ്റിക്സ്',
    logout: 'ലോഗൗട്ട്',
    menu: 'മെനു',
    download_app: 'ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
    change_language: 'ഭാഷ മാറ്റുക',
    dark_mode: 'ഡാർക്ക് മോഡ്',
    light_mode: 'ലൈറ്റ് മോഡ്',
    contact_us: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    back: 'പിന്നിലേക്ക്',
    total_members: 'ആകെ അംഗങ്ങൾ',
    monthly_revenue: 'പ്രതിമാസ വരുമാനം',
    this_month: 'ഈ മാസം',
    search_members: 'അംഗങ്ങളെ തിരയുക...',
    renew: 'പുതുക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    delete: 'ഡിലീറ്റ് ചെയ്യുക',
    no_members: 'അംഗങ്ങളെയൊന്നും കണ്ടെത്തിയില്ല',
    loading: 'ലോഡിംഗ്...',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    name: 'പേര്',
    phone: 'ഫോൺ',
    amount: 'തുക',
    days: 'ദിവസങ്ങൾ',
    start_date: 'ആരംഭ തീയതി',
    end_date: 'അവസാന തീയതി',
  },
  or: {
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    active_members: 'ସକ୍ରିୟ ସଦସ୍ୟ',
    ending_membership: 'ଶେଷ ହେଉଥିବା ସଦସ୍ୟତା',
    renew_membership: 'ସଦସ୍ୟତା ନବୀକରଣ',
    add_member: 'ସଦସ୍ୟ ଯୋଡନ୍ତୁ',
    gym_of_fame: 'ଜିମ୍ ଅଫ୍ ଫେମ୍',
    analytics: 'ବିଶ୍ଳେଷଣ',
    logout: 'ଲଗଆଉଟ୍',
    menu: 'ମେନୁ',
    download_app: 'ଆପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    change_language: 'ଭାଷା ବଦଳାନ୍ତୁ',
    dark_mode: 'ଡାର୍କ ମୋଡ୍',
    light_mode: 'ଲାଇଟ୍ ମୋଡ୍',
    contact_us: 'ଯୋଗାଯୋଗ କରନ୍ତୁ',
    back: 'ପଛକୁ',
    total_members: 'ମୋଟ ସଦସ୍ୟ',
    monthly_revenue: 'ମାସିକ ଆୟ',
    this_month: 'ଏହି ମାସ',
    search_members: 'ସଦସ୍ୟ ଖୋଜନ୍ତୁ...',
    renew: 'ନବୀକରଣ',
    edit: 'ସଂପାଦନ',
    delete: 'ଡିଲିଟ୍',
    no_members: 'କୌଣସି ସଦସ୍ୟ ମିଳିଲେ ନାହିଁ',
    loading: 'ଲୋଡ୍ ହେଉଛି...',
    select_language: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
    name: 'ନାମ',
    phone: 'ଫୋନ୍',
    amount: 'ପରିମାଣ',
    days: 'ଦିନ',
    start_date: 'ଆରମ୍ଭ ତାରିଖ',
    end_date: 'ଶେଷ ତାରିଖ',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    active_members: 'ਸਰਗਰਮ ਮੈਂਬਰ',
    ending_membership: 'ਖਤਮ ਹੋਣ ਵਾਲੀ ਮੈਂਬਰਸ਼ਿਪ',
    renew_membership: 'ਮੈਂਬਰਸ਼ਿਪ ਨਵੀਨੀਕਰਨ',
    add_member: 'ਮੈਂਬਰ ਸ਼ਾਮਲ ਕਰੋ',
    gym_of_fame: 'ਜਿਮ ਆਫ ਫੇਮ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    logout: 'ਲੌਗਆਊਟ',
    menu: 'ਮੇਨੂ',
    download_app: 'ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ',
    change_language: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    dark_mode: 'ਡਾਰਕ ਮੋਡ',
    light_mode: 'ਲਾਈਟ ਮੋਡ',
    contact_us: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    back: 'ਪਿੱਛੇ',
    total_members: 'ਕੁੱਲ ਮੈਂਬਰ',
    monthly_revenue: 'ਮਾਸਿਕ ਆਮਦਨ',
    this_month: 'ਇਸ ਮਹੀਨੇ',
    search_members: 'ਮੈਂਬਰ ਲੱਭੋ...',
    renew: 'ਨਵਿਆਓ',
    edit: 'ਸੋਧੋ',
    delete: 'ਹਟਾਓ',
    no_members: 'ਕੋਈ ਮੈਂਬਰ ਨਹੀਂ ਮਿਲਿਆ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    name: 'ਨਾਮ',
    phone: 'ਫੋਨ',
    amount: 'ਰਕਮ',
    days: 'ਦਿਨ',
    start_date: 'ਸ਼ੁਰੂਆਤੀ ਮਿਤੀ',
    end_date: 'ਆਖਰੀ ਮਿਤੀ',
  },
  as: {
    dashboard: 'ড্যাশবোর্ড',
    active_members: 'সক্রিয় সদস্য',
    ending_membership: 'অন্তিম সদস্যপদ',
    renew_membership: 'সদস্যপদ নবীকৰণ',
    add_member: 'সদস্য যোগ কৰক',
    gym_of_fame: 'জিম অফ ফেম',
    analytics: 'বিশ্লেষণ',
    logout: 'লগআউট',
    menu: 'মেনু',
    download_app: 'এপ ডাউনলোড কৰক',
    change_language: 'ভাষা সলনি কৰক',
    dark_mode: 'ডার্ক মোড',
    light_mode: 'লাইট মোড',
    contact_us: 'যোগাযোগ কৰক',
    back: 'পিছলৈ',
    total_members: 'মুঠ সদস্য',
    monthly_revenue: 'মাহিলী আয়',
    this_month: 'এই মাহত',
    search_members: 'সদস্য সন্ধান কৰক...',
    renew: 'নবীকৰণ কৰক',
    edit: 'সম্পাদনা কৰক',
    delete: 'মচি পেলাওক',
    no_members: 'কোনো সদস্য পোৱা নগ’ল',
    loading: 'লোড হৈ আছে...',
    select_language: 'ভাষা বাছনি কৰক',
    name: 'নাম',
    phone: 'ফোন',
    amount: 'পৰিমাণ',
    days: 'দিন',
    start_date: 'আৰম্ভণিৰ তাৰিখ',
    end_date: 'শেষ তাৰিখ',
  },
  ma: {
    dashboard: 'डैशबोर्ड',
    active_members: 'सक्रिय सदस्य',
    ending_membership: 'समाप्त होवय बला सदस्यता',
    renew_membership: 'सदस्यता नवीकरण',
    add_member: 'सदस्य जोडू',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेन्यू',
    download_app: 'ऐप डाउनलोड करू',
    change_language: 'भाषा बदलू',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'संपर्क करू',
    back: 'पाछा',
    total_members: 'कुल सदस्य',
    monthly_revenue: 'मासिक आय',
    this_month: 'ई महिना',
    search_members: 'सदस्य खोजू...',
    renew: 'नवीकरण करू',
    edit: 'संपादित करू',
    delete: 'हटाउ',
    no_members: 'कोनो सदस्य नै भेटल',
    loading: 'लोड भ रहल अछि...',
    select_language: 'भाषा चुनू',
    name: 'नाम',
    phone: 'फोन',
    amount: 'राशि',
    days: 'दिन',
    start_date: 'शुरू होइबक तिथि',
    end_date: 'समाप्ति तिथि',
  },
  sa: {
    dashboard: 'फलकम्',
    active_members: 'सक्रियाः सदस्याः',
    ending_membership: 'समाप्यमानं सदस्यत्वम्',
    renew_membership: 'सदस्यत्वनवीनीकरणम्',
    add_member: 'सदस्यं योजयतु',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषणम्',
    logout: 'निर्गमनम्',
    menu: 'सूचिः',
    download_app: 'अनुप्रयोगं डाउनलोड् कुर्वन्तु',
    change_language: 'भाषां परिवर्तयतु',
    dark_mode: 'कृष्णविधिः',
    light_mode: 'प्रकाशविधिः',
    contact_us: 'सम्पर्कं कुर्वन्तु',
    back: 'पृष्ठतः',
    total_members: 'कुल सदस्याः',
    monthly_revenue: 'मासिक आयः',
    this_month: 'अस्मिन् मासे',
    search_members: 'सदस्यं अन्विषयतु...',
    renew: 'नवीकरोतु',
    edit: 'सम्पादयतु',
    delete: 'लोपयतु',
    no_members: 'कोऽपि सदस्यः न प्राप्तः',
    loading: 'लोड् भवति...',
    select_language: 'भाषां चिनोतु',
    name: 'नाम',
    phone: 'दूरभाषः',
    amount: 'धनराशिः',
    days: 'दिनानि',
    start_date: 'प्रारम्भतिथिः',
    end_date: 'समाप्तितिथिः',
  },
  ks: {
    dashboard: 'डैशबोर्ड',
    active_members: 'सक्रिय मेंबर',
    ending_membership: 'खतम गछन वाल मेंबरशिप',
    renew_membership: 'मेंबरशिप नवीनीकरण',
    add_member: 'मेंबर रलावन',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेन्यू',
    download_app: 'ऐप डाउनलोड करुन',
    change_language: 'ज़बान तब्दील करुन',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'राब्त करुन',
    back: 'पतुन',
    total_members: 'कुल मेंबर',
    monthly_revenue: 'माहवार आमदनी',
    this_month: 'यथ मावस',
    search_members: 'मेंबर तलाश करुन...',
    renew: 'नवीनीकरण करुन',
    edit: 'एडिट करुन',
    delete: 'हटावन',
    no_members: 'कान्ह मेंबर नी मिल्यव',
    loading: 'लोड गछान...',
    select_language: 'ज़बान चुनिव',
    name: 'नाव',
    phone: 'फोन',
    amount: 'रकम्',
    days: 'दह',
    start_date: 'शुरू गछनुक तारिख',
    end_date: 'खतम गछनुक तारिख',
  },
  sd: {
    dashboard: 'ڊيش بورڊ',
    active_members: 'سرگرم ميمبر',
    ending_membership: 'ختم ٿيندڙ ميمبرشپ',
    renew_membership: 'ميمبرشپ جي تجديد',
    add_member: 'ميمبر شامل ڪريو',
    gym_of_fame: 'جم آف فيم',
    analytics: 'تجزيي',
    logout: 'لاگ آئوٽ',
    menu: 'مينيو',
    download_app: 'ايپ ڊائون لوڊ ڪريو',
    change_language: 'ٻولي تبديل ڪريو',
    dark_mode: 'ڊارڪ موڊ',
    light_mode: 'لائيٽ موڊ',
    contact_us: 'رابطو ڪريو',
    back: 'واپس',
    total_members: 'ڪل ميمبر',
    monthly_revenue: 'ماهوار آمدني',
    this_month: 'هن مهيني',
    search_members: 'ميمبر ڳوليو...',
    renew: 'تجديد ڪريو',
    edit: 'ترميم ڪريو',
    delete: 'خارج ڪريو',
    no_members: 'ڪو به ميمبر نه مليو',
    loading: 'لوڊ ٿي رهيو آهي...',
    select_language: 'ٻولي چونڊيو',
    name: 'نالو',
    phone: 'فون',
    amount: 'رقم',
    days: 'ڏينهن',
    start_date: 'شروع ٿيڻ جي تاريخ',
    end_date: 'ختم ٿيڻ جي تاريخ',
  },
  ur: {
    dashboard: 'ڈیش بورڈ',
    active_members: 'فعال اراکین',
    ending_membership: 'ختم ہونے والی رکنیت',
    renew_membership: 'رکنیت کی تجدید',
    add_member: 'ممبر شامل کریں',
    gym_of_fame: 'جم آف فیم',
    analytics: 'تجزیہ',
    logout: 'لاگ آؤٹ',
    menu: 'مینو',
    download_app: 'ایپ ڈاؤن لوڈ کریں',
    change_language: 'زبان تبدیل کریں',
    dark_mode: 'ڈارک موڈ',
    light_mode: 'لائٹ موڈ',
    contact_us: 'رابطہ کریں',
    back: 'پیچھے',
    total_members: 'کل اراکین',
    monthly_revenue: 'ماہانہ آمدنی',
    this_month: 'اس ماہ',
    search_members: 'ممبر تلاش کریں...',
    renew: 'تجدید کریں',
    edit: 'ترمیم کریں',
    delete: 'حذف کریں',
    no_members: 'کوئی ممبر نہیں ملا',
    loading: 'لوڈنگ...',
    select_language: 'زبان منتخب کریں',
    name: 'نام',
    phone: 'فون',
    amount: 'رقم',
    days: 'دن',
    start_date: 'شروع کی تاریخ',
    end_date: 'ختم کی تاریخ',
  },
  ko: {
    dashboard: 'डॅशबोर्ड',
    active_members: 'सक्रीय सदस्य',
    ending_membership: 'सोपपी सदस्यपण',
    renew_membership: 'सदस्यपण नूतनीकरण',
    add_member: 'वांगडी जोडूंक',
    gym_of_fame: 'जिम ऑफ फेमस',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेन्यू',
    download_app: 'अॅप डाउनलोड करा',
    change_language: 'भास बदलूंक',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाईट मोड',
    contact_us: 'संपर्क करा',
    back: 'फाटीं',
    total_members: 'एकुण वांगडी',
    monthly_revenue: 'म्हयन्याची येणावळ',
    this_month: 'ह्या म्हयन्यांत',
    search_members: 'वांगडी सोदूक...',
    renew: 'नूतनीकरण करा',
    edit: 'सुधारणा करा',
    delete: 'काडून उडय',
    no_members: 'कोणीच वांगडी मेळ्ळो ना',
    loading: 'लोड जाता...',
    select_language: 'भास निवडा',
    name: 'नांव',
    phone: 'फोन',
    amount: 'रक्कम',
    days: 'दीस',
    start_date: 'सुरुवात तारीख',
    end_date: 'सोंपवपाची तारीख',
  },
  mn: {
    dashboard: 'ড্যাশবোর্ড',
    active_members: 'এক্টিভ মেম্বরশিং',
    ending_membership: 'লোইশিগদৌরিবা মেম্বরশিপ',
    renew_membership: 'মেম্বরশিপ রিনিউ তৌবা',
    add_member: 'মেম্বর হাপ্পা',
    gym_of_fame: 'জিম অফ ফেম',
    analytics: 'এনালাইটিক্স',
    logout: 'লগআউট',
    menu: 'মেন্যু',
    download_app: 'এপ ডাউনলোড তৌবীয়ু',
    change_language: 'লোন হোংদোকপা',
    dark_mode: 'ডার্ক মোড',
    light_mode: 'লাইট মোড',
    contact_us: 'পাউ ফাওবীয়ু',
    back: 'হন্দোকপা',
    total_members: 'অপুনবা মেম্বরশিং',
    monthly_revenue: 'থাগী ওইবা ইনকম',
    this_month: 'থা অসিদা',
    search_members: 'মেম্বর থিবীয়ু...',
    renew: 'রিনিউ তৌবীয়ু',
    edit: 'শেমদোকপা',
    delete: 'মুত্থতপা',
    no_members: 'মেম্বর অমাত্তা ফংদে',
    loading: 'লোডিং...',
    select_language: 'লোন খল্লীয়ু',
    name: 'মিং',
    phone: 'ফোন',
    amount: 'শেনফম',
    days: 'নুমিত',
    start_date: 'হৌবা তারিখ',
    end_date: 'লোইবা তারিখ',
  },
  bo: {
    dashboard: 'ড্যাশবোর্ড',
    active_members: 'সক্রিয় সদস্য',
    ending_membership: 'জবাইনাই মেম্বারশিপ',
    renew_membership: 'মেম্বারশিপ গোদান তৌফին',
    add_member: 'মেম্বার ফিন',
    gym_of_fame: 'জিম অফ ফেম',
    analytics: 'এনালিটিক্স',
    logout: 'লগআউট',
    menu: 'মেনু',
    download_app: 'এপ ডাউনলোড তৌ',
    change_language: 'রাও সলাই',
    dark_mode: 'ডার্ক মোড',
    light_mode: 'লাইট মোড',
    contact_us: 'যোগাযোগ তৌ',
    back: 'উনাং',
    total_members: 'গাসি মেম্বার',
    monthly_revenue: 'দানসে ইনকম',
    this_month: 'বে দানসাও',
    search_members: 'মেম্বার নাগির...',
    renew: 'গোদান তৌ',
    edit: 'শেমফাত তৌ',
    delete: 'মুত্থাই',
    no_members: 'মেম্বার গৈয়া',
    loading: 'লোড জাবায়...',
    select_language: 'রাও বাছি',
    name: 'মুং',
    phone: 'ফোন',
    amount: 'টাকা',
    days: 'সান',
    start_date: 'জাগায়নায় তারিখ',
    end_date: 'জবাইনাই তারিখ',
  },
  do: {
    dashboard: 'डैशबोर्ड',
    active_members: 'सक्रिय सदस्य',
    ending_membership: 'खतम होन आह्ली मेंबरशिप',
    renew_membership: 'मेंबरशिप दा नवीकरण',
    add_member: 'मेंबर जोड़ो',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेन्यू',
    download_app: 'ऐप डाउनलोड करो',
    change_language: 'बोली बदलो',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'राब्ता करो',
    back: 'पिछें',
    total_members: 'कुल्ल सदस्य',
    monthly_revenue: 'महीने दी कमाई',
    this_month: 'इस महीने',
    search_members: 'मेंबर लब्भो...',
    renew: 'नवीकरण करो',
    edit: 'ठीक करो',
    delete: 'हटाओ',
    no_members: 'कोई सदस्य नेईं मिल्या',
    loading: 'लोड होआ करदा ऐ...',
    select_language: 'बोली चुनो',
    name: 'नाम',
    phone: 'फोन',
    amount: 'रकम',
    days: 'दिन',
    start_date: 'शुरू होने दी तारीख',
    end_date: 'खतम होने दी तारीख',
  },
  ne: {
    dashboard: 'ड्यासबোর্ড',
    active_members: 'सक्रिय सदस्यहरू',
    ending_membership: 'सकिन लागेको सदस्यता',
    renew_membership: 'सदस्यता नवीकरण',
    add_member: 'सदस्य थप्नुहोस्',
    gym_of_fame: 'जिम अफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लगआउट',
    menu: 'मेनु',
    download_app: 'एप डाउनलोड गर्नुहोस्',
    change_language: 'भाषा परिवर्तन गर्नुहोस्',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'सम्पर्क गर्नुहोस्',
    back: 'पछाडि',
    total_members: 'कुल सदस्यहरू',
    monthly_revenue: 'मासिक आम्दानी',
    this_month: 'यस महिना',
    search_members: 'सदस्य खोज्नुहोस्...',
    renew: 'नवीकरण गर्नुहोस्',
    edit: 'सम्पादन गर्नुहोस्',
    delete: 'हटाउनुहोस्',
    no_members: 'कुनै सदस्य भेटिएन',
    loading: 'लोड हुँदैछ...',
    select_language: 'भाषा छनोट गर्नुहोस्',
    name: 'नाम',
    phone: 'फोन',
    amount: 'रकम',
    days: 'दिन',
    start_date: 'सुरुवात मिति',
    end_date: 'समाप्ति मिति',
  },
  st: {
    dashboard: 'डैशबोर्ड',
    active_members: 'सक्रिय सदानि',
    ending_membership: 'मुचुक़ सदानि',
    renew_membership: 'सदानि नवीकरण',
    add_member: 'सदानि जोडाव',
    gym_of_fame: 'जिम ऑफ फेम',
    analytics: 'विश्लेषण',
    logout: 'लॉगआउट',
    menu: 'मेन्यू',
    download_app: 'ऐप डाउनलोड मे',
    change_language: 'रोड़ बदलावा',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    contact_us: 'संपर्क मे',
    back: 'तायम',
    total_members: 'जोतो सदानि',
    monthly_revenue: 'चांदो कमाई',
    this_month: 'नुवा चांदो',
    search_members: 'सदानि पांतेय...',
    renew: 'नवीकरण मे',
    edit: 'सुधार मे',
    delete: 'गिडा़व मे',
    no_members: 'कोय सदानि बांको नाम लेद कवा',
    loading: 'लोडो काना...',
    select_language: 'रोड़ बाछाव मे',
    name: 'नुतुम',
    phone: 'फोन',
    amount: 'टाका',
    days: 'दिन्',
    start_date: 'एतोहब तारिख',
    end_date: 'मुचाद तारिख',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('app_lang') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
